int = int(input())
float= float(input())
str=input()
list=input().split()
tuple=tuple(input().split())
set=set(input().split())
list of int - list(map(int,input().split()))
tuple of int -tuple(map(int,input().split()))
set of int-set(map(int,input().split()))
list of float -list(map(float,input().split()))
